require:
  - rubocop-rspec
  - rubocop-performance

inherit_gem:
  rentacop:
    - rentacop.yml
    - rspec.yml

AllCops:
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  Exclude:
    - 'dev/**/*'
    - 'example/**/*'
    - 'demo/**/*'

# Allow `expect_any_instance_of`
RSpec/AnyInstance:
  Enabled: false

# Using `expect` instead of `allow` is needed here, otherwise test coverage
# falls below 100%
RSpec/StubbedMock:
  Exclude:
    - spec/rspec_approvals/approval_handler_spec.rb