language: ruby

env:
  global:
  - CC_TEST_REPORTER_ID=22face453d8d53f921a12f5489db59e8d00bdbb951fce53b72cd69e05bfa72d5

rvm:
  - "2.3.1"
  - "2.4.2"
  - "2.5.0"

notifications:
  email: false

before_install:
- gem install bundler

before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build

script:
- bundle exec rspec

after_script: 
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT